/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as CustomerTimelineRouteImport } from './routes/customer.timeline'
import { Route as CustomerSimLockRouteImport } from './routes/customer.sim-lock'
import { Route as CustomerSettingsRouteImport } from './routes/customer.settings'
import { Route as CustomerDevicesRouteImport } from './routes/customer.devices'
import { Route as CustomerAnalyticsRouteImport } from './routes/customer.analytics'
import { Route as CustomerActivityRouteImport } from './routes/customer.activity'
import { Route as AgentVerificationRouteImport } from './routes/agent.verification'
import { Route as AgentRiskRouteImport } from './routes/agent.risk'
import { Route as AgentAuditRouteImport } from './routes/agent.audit'
import { Route as AgentApprovalRouteImport } from './routes/agent.approval'

const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const CustomerTimelineRoute = CustomerTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSimLockRoute = CustomerSimLockRouteImport.update({
  id: '/sim-lock',
  path: '/sim-lock',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerDevicesRoute = CustomerDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAnalyticsRoute = CustomerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerActivityRoute = CustomerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => CustomerRoute,
} as any)
const AgentVerificationRoute = AgentVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AgentRoute,
} as any)
const AgentRiskRoute = AgentRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAuditRoute = AgentAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AgentRoute,
} as any)
const AgentApprovalRoute = AgentApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/agent/approval': typeof AgentApprovalRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/risk': typeof AgentRiskRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/customer/activity': typeof CustomerActivityRoute
  '/customer/analytics': typeof CustomerAnalyticsRoute
  '/customer/devices': typeof CustomerDevicesRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/sim-lock': typeof CustomerSimLockRoute
  '/customer/timeline': typeof CustomerTimelineRoute
  '/agent/': typeof AgentIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/approval': typeof AgentApprovalRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/risk': typeof AgentRiskRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/customer/activity': typeof CustomerActivityRoute
  '/customer/analytics': typeof CustomerAnalyticsRoute
  '/customer/devices': typeof CustomerDevicesRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/sim-lock': typeof CustomerSimLockRoute
  '/customer/timeline': typeof CustomerTimelineRoute
  '/agent': typeof AgentIndexRoute
  '/customer': typeof CustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/agent/approval': typeof AgentApprovalRoute
  '/agent/audit': typeof AgentAuditRoute
  '/agent/risk': typeof AgentRiskRoute
  '/agent/verification': typeof AgentVerificationRoute
  '/customer/activity': typeof CustomerActivityRoute
  '/customer/analytics': typeof CustomerAnalyticsRoute
  '/customer/devices': typeof CustomerDevicesRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/sim-lock': typeof CustomerSimLockRoute
  '/customer/timeline': typeof CustomerTimelineRoute
  '/agent/': typeof AgentIndexRoute
  '/customer/': typeof CustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/customer'
    | '/agent/approval'
    | '/agent/audit'
    | '/agent/risk'
    | '/agent/verification'
    | '/customer/activity'
    | '/customer/analytics'
    | '/customer/devices'
    | '/customer/settings'
    | '/customer/sim-lock'
    | '/customer/timeline'
    | '/agent/'
    | '/customer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/approval'
    | '/agent/audit'
    | '/agent/risk'
    | '/agent/verification'
    | '/customer/activity'
    | '/customer/analytics'
    | '/customer/devices'
    | '/customer/settings'
    | '/customer/sim-lock'
    | '/customer/timeline'
    | '/agent'
    | '/customer'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/customer'
    | '/agent/approval'
    | '/agent/audit'
    | '/agent/risk'
    | '/agent/verification'
    | '/customer/activity'
    | '/customer/analytics'
    | '/customer/devices'
    | '/customer/settings'
    | '/customer/sim-lock'
    | '/customer/timeline'
    | '/agent/'
    | '/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/customer/timeline': {
      id: '/customer/timeline'
      path: '/timeline'
      fullPath: '/customer/timeline'
      preLoaderRoute: typeof CustomerTimelineRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/sim-lock': {
      id: '/customer/sim-lock'
      path: '/sim-lock'
      fullPath: '/customer/sim-lock'
      preLoaderRoute: typeof CustomerSimLockRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/devices': {
      id: '/customer/devices'
      path: '/devices'
      fullPath: '/customer/devices'
      preLoaderRoute: typeof CustomerDevicesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/analytics': {
      id: '/customer/analytics'
      path: '/analytics'
      fullPath: '/customer/analytics'
      preLoaderRoute: typeof CustomerAnalyticsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/activity': {
      id: '/customer/activity'
      path: '/activity'
      fullPath: '/customer/activity'
      preLoaderRoute: typeof CustomerActivityRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/agent/verification': {
      id: '/agent/verification'
      path: '/verification'
      fullPath: '/agent/verification'
      preLoaderRoute: typeof AgentVerificationRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/risk': {
      id: '/agent/risk'
      path: '/risk'
      fullPath: '/agent/risk'
      preLoaderRoute: typeof AgentRiskRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/audit': {
      id: '/agent/audit'
      path: '/audit'
      fullPath: '/agent/audit'
      preLoaderRoute: typeof AgentAuditRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/approval': {
      id: '/agent/approval'
      path: '/approval'
      fullPath: '/agent/approval'
      preLoaderRoute: typeof AgentApprovalRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AgentRouteChildren {
  AgentApprovalRoute: typeof AgentApprovalRoute
  AgentAuditRoute: typeof AgentAuditRoute
  AgentRiskRoute: typeof AgentRiskRoute
  AgentVerificationRoute: typeof AgentVerificationRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentApprovalRoute: AgentApprovalRoute,
  AgentAuditRoute: AgentAuditRoute,
  AgentRiskRoute: AgentRiskRoute,
  AgentVerificationRoute: AgentVerificationRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface CustomerRouteChildren {
  CustomerActivityRoute: typeof CustomerActivityRoute
  CustomerAnalyticsRoute: typeof CustomerAnalyticsRoute
  CustomerDevicesRoute: typeof CustomerDevicesRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  CustomerSimLockRoute: typeof CustomerSimLockRoute
  CustomerTimelineRoute: typeof CustomerTimelineRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerActivityRoute: CustomerActivityRoute,
  CustomerAnalyticsRoute: CustomerAnalyticsRoute,
  CustomerDevicesRoute: CustomerDevicesRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
  CustomerSimLockRoute: CustomerSimLockRoute,
  CustomerTimelineRoute: CustomerTimelineRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
